server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: postgres
    password: qwerty007
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: false

  freemarker:
    enabled: true
    template-loader-path: /WEB-INF/templates
    suffix: .ftl

  mail:
    host: smtp.gmail.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_APPS_PASSWORD}
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          connectionTimeout: 5000
          timeout: 5000
          writeTimeout: 5000

mail:
  base-url: http://localhost:8080
  sender: Test Application
  from: ${spring.mail.username}
  subject: Please verify your account
  content: "Dear $name, please follow the link below to verify your account: <a href=$url>VERIFY</a>"